# Generated by Django 6.0.3 on 2026-05-12 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoproducto',
            name='alquiler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.alquiler'),
        ),
        migrations.AddField(
            model_name='movimientoproducto',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.reservaevento'),
        ),
        migrations.AddField(
            model_name='movimientoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
    ]
