# Generated by Django 6.0.3 on 2026-05-12 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.BigIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('nivel_educativo', models.CharField(blank=True, choices=[('Bachiller', 'Bachiller'), ('Tecnico', 'Tecnico'), ('Tecnologo', 'Tecnologo'), ('Profesional', 'Profesional')], max_length=20, null=True)),
                ('referencia_personal', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_referencia_personal', models.CharField(blank=True, max_length=20, null=True)),
                ('eps', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol')),
            ],
        ),
    ]
