# Generated by Django 6.0.3 on 2026-05-12 05:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('paquetes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('capacidad_maxima', models.PositiveIntegerField()),
                ('precio_renta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='lugares/')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MenuComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio_por_persona', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('mora_diaria', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=10)),
                ('valor_mora', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('estado', models.CharField(choices=[('Reservado', 'Reservado'), ('Confirmado', 'Confirmado'), ('En Curso', 'En Curso'), ('Devuelto', 'Devuelto'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Reservado', max_length=20)),
                ('incluye_transporte', models.BooleanField(default=False)),
                ('costo_transporte', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('valor_alquiler', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('deposito_garantia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('valor_danos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('hora_inicio', models.TimeField(null=True)),
                ('hora_fin_limpieza', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deposito_garantia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('asistentes', models.PositiveIntegerField(default=0)),
                ('precio_paquete', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado_deposito', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Retenido', 'Retenido'), ('Devuelto', 'Devuelto'), ('Usado', 'Usado')], default='Pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('Reservado', 'Reservado'), ('Confirmado', 'Confirmado'), ('En Preparacion', 'En Preparacion'), ('Evento Activo', 'Evento Activo'), ('Evaluacion', 'Evaluacion'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Reservado', max_length=20)),
                ('lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.lugar')),
                ('menu_comida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.menucomida')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paquetes.paquete')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta')], max_length=20)),
                ('tipo', models.CharField(choices=[('Anticipo', 'Anticipo'), ('Parcial', 'Parcial'), ('Final', 'Final'), ('Deposito', 'Deposito'), ('Reembolso', 'Reembolso')], default='Parcial', max_length=20)),
                ('alquiler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.alquiler')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.reservaevento')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_danada', models.IntegerField(default=0)),
                ('costo_dano', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.reservaevento')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario_fijado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='operaciones.reservaevento')),
            ],
        ),
        migrations.CreateModel(
            name='AlquilerProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_contratada', models.PositiveIntegerField()),
                ('cantidad_retornada_ok', models.PositiveIntegerField(default=0)),
                ('cantidad_danada', models.PositiveIntegerField(default=0)),
                ('precio_alquiler_fijado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_danos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacion_dano', models.CharField(blank=True, max_length=255, null=True)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.alquiler')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
            options={
                'unique_together': {('alquiler', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_fijado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_extra', to='operaciones.reservaevento')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paquetes.servicio')),
            ],
            options={
                'unique_together': {('reserva', 'servicio')},
            },
        ),
    ]
