# Generated by Django 6.0.3 on 2026-05-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tarjeta_tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='tarjeta_titular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='transferencia_banco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='transferencia_numero',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='transferencia_tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo',
            field=models.CharField(choices=[('Anticipo', 'Anticipo'), ('Parcial', 'Parcial'), ('Final', 'Final'), ('Deposito', 'Deposito'), ('Reembolso', 'Reembolso')], default='Final', max_length=20),
        ),
    ]
