# Generated by Django 6.0.3 on 2026-06-23 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_pago_tarjeta_tipo_pago_tarjeta_titular_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaevento',
            name='organizador_encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_supervisados', to='usuarios.usuario', verbose_name='Organizador Encargado'),
        ),
    ]
