# Generated by Django 6.0.3 on 2026-07-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_reservaevento_organizador_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='novedad',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de la inactivación'),
        ),
    ]
