# Generated by Django 6.0.3 on 2026-06-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='precio',
            new_name='precio_servicio',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='nombre',
        ),
        migrations.AddField(
            model_name='servicio',
            name='costo_proveedor',
            field=models.IntegerField(default=0, verbose_name='Lo que cobra el externo a Arron'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='nit_o_cedula_proveedor',
            field=models.CharField(default='000000000', max_length=20, verbose_name='NIT o Cédula'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombre_empresa_externa',
            field=models.CharField(default='Independiente', max_length=100, verbose_name='Empresa Proveedora'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombre_proveedor',
            field=models.CharField(default='Por Asignar', max_length=100, verbose_name='Nombre del Especialista / Contacto'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombre_servicio',
            field=models.CharField(default='Servicio Antiguo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='telefono_proveedor',
            field=models.CharField(default='0000000000', max_length=15, verbose_name='Teléfono de Contacto'),
        ),
    ]
